see changelog

diff --git a/functions/digall b/functions/digall
--- a/functions/digall
+++ b/functions/digall
@@ -1,16 +1,21 @@
 # Function to retrieve most of DIG (A,AAAA,CAA,CNAME,DS,LOC,MX,NS,PTR,SPF,SRV,HINFO,ISDN,TXT,SOA) if available.
+# You can set a resolver with enironment variable DIGALL_RESOLVER
+# DIGALL_RESOLVER=8.8.8.8 digall example.com
 function digall() {
-  if ! [[ -z ${1} ]]; then
-    local DOMAIN=${1,,}; local RL;
-    host ${DOMAIN} &>/dev/null; if [[ $? -eq 0 ]]; then
-      for DQ in {A,AAAA,CAA,CNAME,DS,LOC,MX,NS,PTR,SPF,SRV,HINFO,ISDN,TXT,SOA}; do
-        RL=$(dig ${DQ} +nocmd +multiline +noall +answer ${DOMAIN} | sed -e "s/${DOMAIN}.\t*/TTL: /");
-        [[ ! -z "${RL}" ]] && echo -e "\033[1;3;4;38;5;90m${DOMAIN^^} ${DQ} RECORDS\033[0m\n${RL}\n";
-      done
-    else
-      echo -e "\033[1;38;5;196mERROR\033[0m: \033[1m${DOMAIN^^}\033[0m is NOT valid." && return 1;
-    fi
-  else
-    echo -e "\033[1;38;5;196mERROR\033[0m: no domain specified." && return 1;
-  fi
-}; alias dig-all='digall';
+	local RESOLVER=${DIGALL_RESOLVER:-1.1.1.1};
+	if ! [[ -z ${1} ]]; then
+		local DOMAIN=${1,,}; local RL;
+		host ${DOMAIN} &>/dev/null;
+		if [[ $? -eq 0 ]]; then
+			for DQ in {A,AAAA,CAA,CNAME,DS,LOC,MX,NS,PTR,SPF,SRV,HINFO,ISDN,TXT,SOA}; do
+				RL=$(dig @${DIGALL_RESOLVER} ${DQ} +nocmd +multiline +noall +answer ${DOMAIN} | sed -e "s/${DOMAIN}.\t*/TTL: /");
+				[[ ! -z "${RL}" ]] && echo -e "\033[1;3;4;38;5;90m${DOMAIN^^} ${DQ} RECORDS\033[0m\n${RL}\n";
+			done
+		else
+			echo -e "\033[1;38;5;196mERROR\033[0m: \033[1m${DOMAIN^^}\033[0m is NOT valid." && return 1;
+		fi
+	else
+		echo -e "\033[1;38;5;196mERROR\033[0m: No domain specified." && return 1;
+	fi
+}
+alias dig-all='digall';
diff --git a/functions/most-used b/functions/most-used
--- a/functions/most-used
+++ b/functions/most-used
@@ -3,19 +3,20 @@
 # Greatly inspired from https://www.commandlinefu.com/commands/view/604/
 #
 function most-used() {
-  local DEFITEMS COUNT;
-  DEFITEMS=12; COUNT=${1};
-  if [[ -z ${COUNT##+(0)} ]]; then
-    >&2 echo -e "\\033[1;4mUsage:\\033[0m\\n\\n    ${FUNCNAME} ITEM_COUNT (optional, default: ${DEFITEMS} items)\\n";
-    HISTTIMEFORMAT= history | awk '{a[$2]++}END{for(i in a){print a[i] " " i}}' | sort -rn | head -n${DEFITEMS}
-  elif [[ ${COUNT} == '-h' || ${COUNT} == '--help' ]]; then
-    echo -e "\\033[1;4mUsage:\\033[0m\\n\\n    ${FUNCNAME} ITEM_COUNT (optional, default: ${DEFITEMS} items)";
-  else
-    if [[ ${COUNT##+(0)} =~ ^[0-9]+$ ]]; then
-      HISTTIMEFORMAT= history | awk '{a[$2]++}END{for(i in a){print a[i] " " i}}' | sort -rn | head -n${COUNT}
-    else
-      echo -e "\\033[1;38;5;160mERROR\\033[0;1m:\\033[0m Invalid input. Must be of integer value.";
-      return 1;      
-    fi
-  fi
-}; alias mostused='most-used';
+	local DEFITEMS COUNT;
+	DEFITEMS=12; COUNT=${1};
+	if [[ -z ${COUNT##+(0)} ]]; then
+		>&2 echo -e "\\033[1;4mUsage:\\033[0m\\n\\n    ${FUNCNAME} ITEM_COUNT (optional, default: ${DEFITEMS} items)\\n";
+		HISTTIMEFORMAT= history | awk '{a[$2]++}END{for(i in a){print a[i] " " i}}' | sort -rn | head -n${DEFITEMS}
+		elif [[ ${COUNT} == '-h' || ${COUNT} == '--help' ]]; then
+		echo -e "\\033[1;4mUsage:\\033[0m\\n\\n    ${FUNCNAME} ITEM_COUNT (optional, default: ${DEFITEMS} items)";
+	else
+		if [[ ${COUNT##+(0)} =~ ^[0-9]+$ ]]; then
+			HISTTIMEFORMAT= history | awk '{a[$2]++}END{for(i in a){print a[i] " " i}}' | sort -rn | head -n${COUNT}
+		else
+			echo -e "\\033[1;38;5;196mERROR\\033[0;1m:\\033[0m Invalid input. Must be of integer value.";
+			return 1;      
+		fi
+	fi
+}
+alias mostused='most-used';
diff --git a/functions/pidof-parent b/functions/pidof-parent
--- a/functions/pidof-parent
+++ b/functions/pidof-parent
@@ -1,8 +1,18 @@
 # Function to retrieve a process's parent pid. Simply call with any
 # process name to retrieve it's PPID. 'pidof-parent nginx' per example.
+#
+# Todo: at some point check if input is numerical
+#
 function pidof-parent() {
-  [[ -z ${1} ]] && { >&2 echo -e "\033[1;38;5;196mERROR\033[0m: no process name specified." && return 1; }
-  local _PROC=$(echo "${1}"); local _PPID=$(ps hf -o pid -C "${_PROC}" | awk '{print $1; exit}' 2>/dev/null);
-  [[ -z ${_PPID} ]] && { >&2 echo -e "\033[1;38;5;196mERROR\033[0m: no such process."; return 1; }
-  echo ${_PPID};
+	local _PROC _PPID;
+	if [[ -z ${1} ]]; then
+		>&2 echo -e "\033[1;38;5;196mERROR\033[0m: No process name specified."; return 1;
+	else
+		_PROC=$(echo "${1}"); _PPID=$(ps hf -o pid -C "${_PROC}" | awk '{print $1; exit}' 2>/dev/null);
+
+		if [[ -z ${_PPID} ]]; then
+			>&2 echo -e "\033[1;38;5;196mERROR\033[0m: No such process."; return 1;
+		fi
+		echo ${_PPID};
+	fi
 }
